name: Build, Test & Publish UI Components React

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'rollup.config.js'
      - 'tsconfig.json'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check NPM Token
      run: |
        if [ -z "${{ secrets.NPM_GITHUB_ACTION_AUTO }}" ]; then
          echo "NPM_GITHUB_ACTION_AUTO secret not found - publishing will be skipped"
          echo "NPM_GITHUB_ACTION_AUTO_available=false" >> $GITHUB_OUTPUT
        else
          echo "NPM_GITHUB_ACTION_AUTO found - publishing enabled"
          echo "NPM_GITHUB_ACTION_AUTO_available=true" >> $GITHUB_OUTPUT
        fi
      id: token_check
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run type checking
      run: |
        if [ -d "node_modules/@tamyla/ui-components" ]; then
          echo "Found @tamyla/ui-components - running type check"
          npm run type-check
        else
          echo "Skipping type checking - @tamyla/ui-components not available in node_modules"
          echo "This is expected when the base package hasn't been published yet"
        fi
      continue-on-error: true
    
    - name: Run CommonJS check
      run: npm run check:cjs
    
    # - name: Run linting
    #   run: npm run lint
    #   continue-on-error: true
    
    - name: Run tests
      run: npm run test
      continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build package
      run: npm run build
    
    - name: Test package creation
      run: npm pack --dry-run
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files-react
        path: dist/
        retention-days: 30

  publish:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        scope: '@tamyla'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build for production
      run: npm run prepublishOnly
    
    - name: Get package version
      id: package-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_ACTION_AUTO }}
      run: |
        # Check if NPM_GITHUB_ACTION_AUTO is available
        if [ -z "$NODE_AUTH_TOKEN" ]; then
          echo "NPM_GITHUB_ACTION_AUTO not available - skipping publish"
          exit 0
        fi
        
        # Check if this version is already published
        VERSION="${{ steps.package-version.outputs.version }}"
        if npm view @tamyla/ui-components-react@$VERSION version 2>/dev/null; then
          echo "Version $VERSION already published, skipping..."
          exit 0
        fi
        
        # Publish the package
        npm publish --access public
        echo "Published @tamyla/ui-components-react@$VERSION to NPM"
    
    - name: Create GitHub Release
      if: success()
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.version }}
        release_name: Release v${{ steps.package-version.outputs.version }}
        body: |
          ## What's Changed
          - UI Components React package updated to v${{ steps.package-version.outputs.version }}
          - Built and published automatically via GitHub Actions
        draft: false
        prerelease: false
